name: gcl36
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.6.13=h12debd9_1
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==1.4.0
      - cmake==3.28.4
      - dataclasses==0.8
      - distro==1.9.0
      - faiss-cpu==1.6.3
      - faiss-gpu==1.6.3
      - future==0.18.3
      - grpcio==1.48.2
      - h5py==2.10.0
      - importlib-metadata==4.8.3
      - joblib==1.1.1
      - markdown==3.3.7
      - metric-learn==0.7.0
      - numpy==1.19.5
      - opencv-python==4.1.2.30
      - opencv-python-headless==4.1.2.30
      - packaging==21.3
      - pillow==8.4.0
      - pip==21.3.1
      - protobuf==3.19.6
      - pyparsing==2.4.7
      - pyyaml==6.0.1
      - scikit-build==0.16.7
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - setuptools==59.6.0
      - six==1.16.0
      - tensorboard==1.14.0
      - threadpoolctl==3.1.0
      - torch==1.2.0
      - torchvision==0.4.0
      - typing-extensions==4.1.1
      - werkzeug==2.0.3
      - wheel==0.37.1
      - zipp==3.6.0
prefix: /home/matteo/miniconda3/envs/gcl36
